[package]
name = "message"
version = "0.1.0"
authors = ["Pete Hayes <pete@hayes.id.au>"]
edition = "2018"

[dependencies]
bytes = "0.4"
error-chain = "0.12"
pattern-matcher = { version = "0.1", path = "../pattern-matcher" }
tokio-codec = "0.1"
